### ISSUE TITLE
Booklet (questions) to answer with your implementation

### ISSUE THREAD

**Issue by yvan-sraka** [TheoHd/crab-cleaner#1]
## Questions / Answers

**Can you explain to me how your program works and what's this purpose?**

**Can you describe the syntax of a `.crc` file?**

**Please write a parser of the `.crc` syntax using https://github.com/Geal/nom**

**When a `.crc` file contains syntax errors please indicate them by an error message to the user where the error is located.**

**Offer a `--dry-run` mode that allows you to list the files that will be deleted without deleting them.**

**Offer an `--interactive` mode in which the user can preview the files to be deleted one by one.**

**Offer a Terminal UI as we demonstrated in class:**

```rust
use cursive::views::{Dialog, TextView};

fn main() {
    // Creates the cursive root - required for every application.
    let mut siv = cursive::default();

    // Creates a dialog with a single "Quit" button
    siv.add_layer(Dialog::around(TextView::new("Did you like the Rust lecture?"))
                         .title("Rust Lecture")
                         .button("Yes", |s| s.quit())
                         .button("No", |s| s.quit()));

    // Starts the event loop.
    siv.run();
}
```

**Comment by TheoHd** [comment]
Good morning M. Sraka,

As you specified, we added the following features on the repository : 
- What is a `.crc` file ? => in the README.md
- `--dry-run` mode => to inform the user of all files that are affected without modifying or moving them
- `--interactive` mode => to preview the files that are going to be modified or moved

Nevertheless the Terminal UI is scheduled in August, for the moment `cursive` crate is not stable on Windows, and that even the simple example you provided, doesn't actually work even with all the necessary tools installed manually.

As you can see in the README.md, the parser will be improved with https://github.com/Geal/nom as we improve CrabCleaner.
